
# title: Researcher
# url: "https://ankitsultana.com"
title: Usama Sadiq
# url: ""

# Keep this line always comment.
# baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

# remote_theme: ankitsultana/researcher@gem
remote_theme: usamasadiq706/usamasadiq706.github.io@gem

tracking_id: #


# These are footer settings. These appears at the end of page.
# footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"
footer: yes
footer_url: "https://github.com/usamasadiq706"
footer_text: "Page modified by Usama Sadiq"


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
